#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MESSAGE_FILE_PATH=$1

tail -n +2 $COMMIT_MESSAGE_FILE_PATH > .git/temp
echo "$first_line" > $COMMIT_MESSAGE_FILE_PATH
cat .git/temp >> $COMMIT_MESSAGE_FILE_PATH

branch_name=$(git rev-parse --abbrev-ref HEAD)
issue_number=$(echo "$branch_name" | sed -n 's/issue\([0-9]\{1,\}\)-.*/\1/p')

# if the last line of commit includes #$issue_number, don't add it again
last_line=$(tail -n1 "$COMMIT_MESSAGE_FILE_PATH")
if [ `echo $last_line | grep -c "#$issue_number"` -eq 0 ]; then
  subject=$(cat "$COMMIT_MESSAGE_FILE_PATH" | cut -d':' -f2)
  echo "" >> "$COMMIT_MESSAGE_FILE_PATH"
  echo "#$issue_number" >> "$COMMIT_MESSAGE_FILE_PATH"
fi

